.\"
.\"  Copyright 1993,1998,2014 Toyoda Masashi (mtoyoda@acm.org)
.\"
.\"  (Erutasonized by Taichi Sugiyama: 2013/ 3/26)
.\"
.\"	@(#)erutaso.1
.\"
.TH ERUTASO 1 "March 31, 2014"
.SH NAME
erutaso \- improve your good habit of mistyping
.SH SYNOPSIS
.B erutaso
[
.B \-alFc
]
.SH DESCRIPTION
.B erutaso
is a highly advanced animation program for improving your good habit of mistyping.
.PP
.TP
.B \-a
An accident is occurring. Chitandaeru says "KININARIMASU!".
.TP
.B \-l
Loli version
.TP
.B \-F
She flies like an angel.
.TP
.B \-c
Mayaka Ibara appears instead of Eru Chitanda. ('c'..?)
.PP
.SH SEE ALSO
.BR ls (1)
.SH BUGS
It sometimes lists directory contents.
.SH AUTHOR
Toyoda Masashi (mtoyoda@acm.org)
